name: Deploy Custom Middleware with ASP.NET Core Identity to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Restoring dependencies using relative path
    - name: Restore dependencies
      run: dotnet restore "C:\Users\naram\source\repos\JavaScript-based Client-side Inactivity Timer\JavaScript-based Client-side Inactivity Timer\JavaScript.Web.csproj"  # Path relative to the repository root

    # Building the application using relative path
    - name: Build the application
      run: dotnet build "C:\Users\naram\source\repos\JavaScript-based Client-side Inactivity Timer\JavaScript-based Client-side Inactivity Timer\JavaScript.Web.csproj" --configuration Release  # Path relative to the repository root

    # Publishing the application using relative path
    - name: Publish the application
      run: dotnet publish "C:\Users\naram\source\repos\JavaScript-based Client-side Inactivity Timer\JavaScript-based Client-side Inactivity Timer\JavaScript.Web.csproj" -c Release -o ./publish  # Path relative to the repository root

    # Transferring published files to IIS server
    - name: Transfer Files to IIS Server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: ./publish/
        target: C:\Users\naram\source\repos\JavaScript-based Client-side Inactivity Timer\JavaScript-based Client-side Inactivity Timer\bin\Release\net8.0\publish\Documents  # Update the target path as needed for your IIS server

    # Restarting IIS server
    - name: Restart IIS Server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "powershell.exe Restart-Service -Name 'W3SVC'"
